from . import sales_prediction
from . import sales_prediction_config
from . import sales_dashboard
from . import sales_prediction_dashboard
from . import DemandPrediction
from  . import demand_prediction_alert
from . import demand_prediction_scheduler
from . import customer_segment
from . import res_partner
from . import product_recommendation
from . import promotion_notification
from . import product_promotion
from . import dashboard
